import Foundation

private final class TokenPilotLocalizationBundleMarker: NSObject {}

public enum TokenPilotLocalizer {
    public static func localized(_ key: String, language: TokenPilotLanguage) -> String {
        let effective = effectiveLanguage(for: language)

        if let catalogValue = localizedFromCatalog(key, language: effective) {
            return catalogValue
        }

        switch effective {
        case .ko:
            return koreanFallback[key] ?? key
        case .zhHans:
            return chineseFallback[key] ?? englishFallback[key] ?? key
        case .ja:
            return japaneseFallback[key] ?? englishFallback[key] ?? key
        case .en, .system:
            return englishFallback[key] ?? key
        }
    }

    private static let xcstringsCatalog: [String: [String: String]] = loadXcstringsCatalog()

    private static func localizedFromCatalog(_ key: String, language: TokenPilotLanguage) -> String? {
        if let direct = localizedFromXcstrings(key: key, language: language) {
            return direct
        }

        let placeholder = "__tokenpilot_missing_localized__"
        let tablePriority = ["Localizable", nil]

        for bundle in candidateBundles(for: language) {
            for table in tablePriority {
                let localized = bundle.localizedString(forKey: key, value: placeholder, table: table)
                if localized != placeholder {
                    return localized
                }
            }
        }

        return nil
    }

    private static func localizedFromXcstrings(key: String, language: TokenPilotLanguage) -> String? {
        guard let langCode = language.bundleCode else { return nil }

        if let byLang = xcstringsCatalog[langCode], let value = byLang[key], !value.isEmpty {
            return value
        }

        if langCode != "en", let fallback = xcstringsCatalog["en"], let value = fallback[key], !value.isEmpty {
            return value
        }

        return nil
    }

    private static func loadXcstringsCatalog() -> [String: [String: String]] {
        var catalog: [String: [String: String]] = [:]

        var candidates = Set<URL>()
        candidates.insert(Bundle(for: TokenPilotLocalizationBundleMarker.self).bundleURL)
        candidates.insert(Bundle.main.bundleURL)

        for url in candidates {
            guard let bundle = Bundle(url: url),
                  let sourceURL = bundle.url(forResource: "Localizable", withExtension: "xcstrings") else {
                continue
            }

            guard let data = try? Data(contentsOf: sourceURL),
                  let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                  let strings = json["strings"] as? [String: [String: Any]] else {
                continue
            }

            for (key, entry) in strings {
                guard let localizations = entry["localizations"] as? [String: [String: Any]] else { continue }

                for (locale, localization) in localizations {
                    if let stringUnit = localization["stringUnit"] as? [String: Any],
                       let value = stringUnit["value"] as? String, !value.isEmpty {
                        catalog[locale, default: [:]][key] = value
                    }
                }
            }
        }

        return catalog
    }

    private static func candidateBundles(for language: TokenPilotLanguage) -> [Bundle] {
        var out: [Bundle] = []
        var seen: Set<URL> = []

        func append(_ bundle: Bundle?) {
            guard let bundle else { return }
            if seen.insert(bundle.bundleURL).inserted {
                out.append(bundle)
            }
        }

        append(languageSpecificBundle(for: language, baseBundle: Bundle(for: TokenPilotLocalizationBundleMarker.self)))
        append(Bundle(for: TokenPilotLocalizationBundleMarker.self))
        append(languageSpecificBundle(for: language, baseBundle: Bundle.main))
        append(Bundle.main)

        return out
    }

    private static func languageSpecificBundle(for language: TokenPilotLanguage, baseBundle: Bundle) -> Bundle? {
        guard let code = language.bundleCode else { return nil }
        guard let path = baseBundle.path(forResource: code, ofType: "lproj") else { return nil }
        return Bundle(path: path)
    }

    public static func effectiveLanguage(for language: TokenPilotLanguage) -> TokenPilotLanguage {
        if language != .system {
            return language
        }

        let preferred = Locale.preferredLanguages.first?.lowercased() ?? Locale.current.identifier.lowercased()
        if preferred.hasPrefix("ko") { return .ko }
        // TODO: Add zh-Hant support when Traditional Chinese translations are available
        if preferred.hasPrefix("zh") { return .zhHans }
        if preferred.hasPrefix("ja") { return .ja }
        return .en
    }

    private static let englishFallback: [String: String] = [
        "macOS": "macOS",
        "TG": "TG",
        "DC": "DC",
        "Telegram": "Telegram",
        "Discord": "Discord",
        "Alerts": "Alerts",
        "Daily challenge": "Daily challenge",
        "Daily challenge target": "Challenge target",
        "No telemetry yet": "No telemetry yet",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "manual": "Manual",
        "High": "High",
        "Medium": "Medium",
        "Low": "Low",
        "Manual": "Manual",
        "Not requested": "Not requested",
        "Granted": "Granted",
        "Denied": "Denied",
        "Unknown": "Unknown",
        "Risk": "Risk",
        "Period": "Period",
        "Recent usage": "Recent usage",
        "No data": "No data",
        "Connect a data source.": "Connect a data source.",
        "tok": "tok",
        "est.": "est.",
        "Estimated": "Estimated",
        "Claude Code": "Claude Code",
        "Codex": "Codex",
        "Gemini CLI": "Gemini CLI",
        "LIVE": "LIVE",
        "STALE": "STALE",
        "MOCK": "MOCK",
        "--": "--",
        "Input": "Input",
        "Output": "Output",
        "Cost": "Cost",
        "System Default": "System Default",
        "Local AI usage cockpit": "Local AI usage utility",
        "Connect providers in Settings": "Connect providers in Settings",
        "Connect a provider in Settings": "Connect a provider in Settings",
        "Today tokens": "Today tokens",
        "Highest risk": "Highest risk",
        "Lowest remaining": "Lowest remaining",
        "Nearest reset": "Nearest reset",
        "No limits": "No limits",
        "Avg/request": "Avg/request",
        "Cache tokens": "Cache tokens",
        "Most used": "Most used",
        "Busiest hour": "Busiest hour",
        "Daily cap": "Daily cap",
        "Token saved": "Token saved",
        "No token": "No token",
        "No chat ID": "No chat ID",
        "Chat ID set": "Chat ID set",
        "Enter a bot token first.": "Enter a bot token first.",
        "Telegram OFF by default. Enable only after saving TokenPilot's own bot token.": "Telegram OFF by default. Enable only after saving TokenPilot's own bot token.",
        "Discord notifications": "Discord notifications",
        "Enable Discord Alerts": "Enable Discord Alerts",
        "Saved webhook hidden": "Saved webhook hidden",
        "Discord Webhook URL": "Discord Webhook URL",
        "Webhook saved": "Webhook saved",
        "Webhook saved securely": "Webhook saved securely",
        "No webhook": "No webhook",
        "Save Webhook": "Save Webhook",
        "Replace Webhook": "Replace Webhook",
        "Delete Webhook": "Delete Webhook",
        "Discord webhook saved in TokenPilot Keychain item.": "Discord webhook saved in TokenPilot Keychain item.",
        "Discord webhook deleted.": "Discord webhook deleted.",
        "Discord test message sent.": "Discord test message sent.",
        "Enter a Discord webhook URL first.": "Enter a Discord webhook URL first.",
        "Discord OFF by default. Paste only a Discord channel webhook created for TokenPilot.": "Discord OFF by default. Paste only a Discord channel webhook created for TokenPilot.",
        "Webhook URL is stored in TokenPilot's own Keychain item and is never shown in plain text after saving.": "Webhook URL is stored in TokenPilot's own Keychain item and is never shown in plain text after saving.",
        "Optional Discord Alerts": "Optional Discord Alerts",
        "Create a Discord channel webhook, paste it once, then send a test message.": "Create a Discord channel webhook, paste it once, then send a test message.",
        "Telegram and Discord send only alert messages when enabled.": "Telegram and Discord send only alert messages when enabled.",
        "✅ TokenPilot test alert. Discord notifications are connected.": "✅ TokenPilot test alert. Discord notifications are connected.",
        "Choose telemetry.log": "Choose telemetry.log",
        "Choose your Gemini CLI telemetry log file.": "Choose your Gemini CLI telemetry log file.",
        "Choose Claude status JSON": "Choose Claude status JSON",
        "Choose the Claude statusline JSON file TokenPilot should read.": "Choose the Claude statusline JSON file TokenPilot should read.",
        "Choose Gemini source": "Choose Gemini source",
        "Choose telemetry.log or a Gemini session folder.": "Choose telemetry.log or a Gemini session folder.",
        "Telemetry source": "Telemetry source",
        "You can select telemetry.log or a .gemini session folder.": "You can select telemetry.log or a .gemini session folder.",
        "Selected source path saved, but sandbox bookmark was not created. Choose it again if the sandbox cannot read it.": "Selected source path saved, but sandbox bookmark was not created. Choose it again if the sandbox cannot read it.",
        "Toggle providers shown on Overview. Disabled providers are hidden and not refreshed.": "Toggle providers shown on Overview. Disabled providers are hidden and not refreshed.",
        "Auto-detect sources": "Auto-detect sources",
        "Scans only local default paths and user-selected files.": "Scans only local default paths and user-selected files.",
        "Menu bar status": "Menu bar status",
        "Current menu bar": "Current menu bar",
        "Show selected provider in the menu bar. Disabled providers are skipped.": "Show selected provider in the menu bar. Disabled providers are skipped.",
        "At least one provider must stay enabled.": "At least one provider must stay enabled.",
        "Custom: %d": "Custom: %d",
        "5h usage: %d%%": "5h usage: %d%%",
        "Weekly usage: %d%%": "Weekly usage: %d%%",
        "Limit Hints Connector": "Codex limit hints connector",
        "Use Codex Limit Hints Connector": "Use Codex limit hints connector",
        "Asks the local Codex CLI app-server for account/rateLimits/read. TokenPilot does not read, store, display, or export Codex access tokens.": "Opt-in beta: asks the local Codex CLI app-server for account/rateLimits/read. TokenPilot does not read, store, display, or export Codex access tokens.",
        "Codex app-server limit hints are unofficial and may break if the Codex CLI changes. Disable to fall back to local activity/manual values.": "Unofficial beta via Codex CLI app-server; values are hints, not guaranteed official quota. Disable to fall back to local activity/manual values.",
        "Manual / personal calibration fallback": "Manual limit hints fallback",
        "Use Codex Web Snapshot": "Use Manual Limit Snapshot",
        "Enter values you see on Codex web. TokenPilot stores only these numbers, not cookies or login tokens.": "Enter limit values you saw yourself. TokenPilot stores only these numbers, not cookies or login tokens.",
        "Web today tokens: %d": "Manual today tokens: %d",
        "Mark Web Snapshot Now": "Mark Manual Snapshot Now",
        "Captured": "Captured",
        "Codex web snapshot marked as current.": "Codex manual snapshot marked as current.",
        "Remaining %d%%": "Remaining %d%%",
        "Providers": "Providers",
        "Limit": "limit",
        "Next reset": "Next reset",
        "Last updated": "Last updated",
        "Stable": "Stable",
        "Warning": "Warning",
        "Critical": "Critical",
        "No reset": "No reset",
        "Local log": "Local log",
        "Local source": "Local source",
        "Not web quota": "Not web quota",
        "Export": "Export",
        "Format": "Format",
        "Save": "Save",
        "Latest limit signals": "Latest limit signals",
        "Limit signals are recorded even when token event history is not available.": "Limit signals are recorded even when token event history is not available.",
        "Show latest limit signals": "Show latest limit signals",
        "Hide latest limit signals": "Hide latest limit signals",
        "No token event history yet": "No token event history yet",
        "Showing limit signals until token events arrive.": "Showing limit signals until token events arrive.",
        "Connect Claude JSONL or Gemini telemetry to fill token charts.": "Connect Claude JSONL or Gemini telemetry to fill token charts.",
        "Exports the selected History period only. Credentials, tokens, chat IDs, webhooks, and local file paths are not included.": "Exports selected History usage plus provider summaries. Credentials, secret tokens, chat IDs, webhooks, local file paths, and raw prompt/response text are not included.",
        "Preview sample data when no source is connected": "Preview sample data when no source is connected",
        "Sample preview is optional and off by default so release builds never look connected before setup.": "Sample preview is optional and off by default so release builds never look connected before setup.",
        "defaultClaudePath": "~/Library/Application Support/TokenPilot/claude-statusline.json",
        "defaultGeminiPath1": "~/.gemini/telemetry.log",
        "defaultGeminiPath2": "project-level .gemini/telemetry.log",
        "5h": "5h",
        "Week": "Week",
        "Daily": "Daily",
        "alert.reset.title": "TokenPilot reset",
        "alert.fifty.title": "TokenPilot 50%",
        "alert.eighty.title": "TokenPilot 80%",
        "alert.hundred.title": "TokenPilot limit reached",
        "alert.reset.body": "TokenPilot\n\n%@ reset complete.\nYou're clear to continue.",
        "alert.fifty.body": "TokenPilot\n\n%@ reached 50%%.\nReset: %@",
        "alert.eighty.body": "TokenPilot\n\n%@\nUsage: %d%%\nReset: %@\n\nSuggestion:\nUse %@ until reset.",
        "alert.hundred.body": "TokenPilot\n\n%@ reached 100%%.\nReset in %@.\n\nSuggested switch:\n%@",
        "alert.or": " or ",
        "Telegram is not configured.": "Telegram is not configured.",
        "Telegram URL is invalid.": "Telegram URL is invalid.",
        "Telegram request failed.": "Telegram request failed.",
        "No chat ID found. Send a message to the bot first.": "No chat ID found. Send a message to the bot first.",
        "Discord webhook is not configured.": "Discord webhook is not configured.",
        "Discord webhook URL is invalid.": "Discord webhook URL is invalid.",
        "Discord request failed.": "Discord request failed.",
        "Keychain item contained invalid data.": "Keychain item contained invalid data.",
        "Keychain item not found.": "Keychain item not found.",
        "No notification channel is enabled or configured.": "No notification channel is enabled or configured.",
        "Keychain.status.error": "Keychain returned status %d."
    ]

    private static let chineseFallback: [String: String] = [
        "Claude Code": "Claude Code",
        "Codex": "Codex",
        "Gemini CLI": "Gemini CLI",
        "LIVE": "LIVE",
        "STALE": "过期",
        "MOCK": "模拟",
        "--": "--",
        "Input": "输入",
        "Output": "输出",
        "Cost": "费用",
        "System Default": "系统默认",
        "Local AI usage cockpit": "本地 AI 使用量工具",
        "Connect providers in Settings": "在设置中连接数据源",
        "Connect a provider in Settings": "在设置中连接数据源",
        "Today tokens": "今日 Token",
        "Highest risk": "最高风险",
        "Lowest remaining": "最低剩余",
        "Nearest reset": "最近重置",
        "No limits": "无限额信息",
        "Avg/request": "平均/请求",
        "Daily cap": "每日上限",
        "Token saved": "Token 已保存",
        "No token": "无 Token",
        "No chat ID": "无聊天 ID",
        "Chat ID set": "聊天 ID 已设置",
        "Enter a bot token first.": "请先输入机器人 Token。",
        "Telegram OFF by default. Enable only after saving TokenPilot's own bot token.": "Telegram 默认关闭。请先保存 TokenPilot 专用机器人 Token 后再启用。",
        "Discord notifications": "Discord 通知",
        "Enable Discord Alerts": "启用 Discord 通知",
        "Saved webhook hidden": "已保存的 Webhook 已隐藏",
        "Discord Webhook URL": "Discord Webhook URL",
        "Webhook saved": "Webhook 已保存",
        "Webhook saved securely": "Webhook 已安全保存",
        "No webhook": "无 Webhook",
        "Save Webhook": "保存 Webhook",
        "Replace Webhook": "替换 Webhook",
        "Delete Webhook": "删除 Webhook",
        "Discord webhook saved in TokenPilot Keychain item.": "Discord Webhook 已保存到 TokenPilot Keychain 项。",
        "Discord webhook deleted.": "Discord Webhook 已删除。",
        "Discord test message sent.": "Discord 测试消息已发送。",
        "Enter a Discord webhook URL first.": "请先输入 Discord Webhook URL。",
        "Discord OFF by default. Paste only a Discord channel webhook created for TokenPilot.": "Discord 默认关闭。只粘贴为 TokenPilot 创建的 Discord 频道 Webhook。",
        "Webhook URL is stored in TokenPilot's own Keychain item and is never shown in plain text after saving.": "Webhook URL 会保存到 TokenPilot 自己的 Keychain 项，保存后不会以明文显示。",
        "Optional Discord Alerts": "可选 Discord 通知",
        "Create a Discord channel webhook, paste it once, then send a test message.": "创建 Discord 频道 Webhook，粘贴一次，然后发送测试消息。",
        "Telegram and Discord send only alert messages when enabled.": "启用后，Telegram 和 Discord 只发送提醒消息。",
        "✅ TokenPilot test alert. Discord notifications are connected.": "✅ TokenPilot 测试提醒。Discord 通知已连接。",
        "Choose telemetry.log": "选择 telemetry.log",
        "Choose your Gemini CLI telemetry log file.": "选择 Gemini CLI telemetry 日志文件。",
        "Choose Claude status JSON": "选择 Claude 状态 JSON",
        "Choose the Claude statusline JSON file TokenPilot should read.": "选择 TokenPilot 要读取的 Claude statusline JSON 文件。",
        "Choose Gemini source": "选择 Gemini 数据源",
        "Choose telemetry.log or a Gemini session folder.": "选择 telemetry.log 或 Gemini 会话文件夹。",
        "Telemetry source": "Telemetry 数据源",
        "You can select telemetry.log or a .gemini session folder.": "可以选择 telemetry.log 或 .gemini 会话文件夹。",
        "Selected source path saved, but sandbox bookmark was not created. Choose it again if the sandbox cannot read it.": "已保存数据源路径，但未能创建沙盒书签。如果沙盒无法读取，请重新选择。",
        "Toggle providers shown on Overview. Disabled providers are hidden and not refreshed.": "选择概览中显示的数据源。关闭后会隐藏并停止刷新，但不会删除数据。",
        "Auto-detect sources": "自动检测数据源",
        "Scans only local default paths and user-selected files.": "只扫描本地默认路径和用户选择的文件。",
        "Menu bar status": "菜单栏状态",
        "Current menu bar": "当前菜单栏",
        "Show selected provider in the menu bar. Disabled providers are skipped.": "在菜单栏显示所选数据源。已关闭的数据源会自动跳过。",
        "At least one provider must stay enabled.": "至少需要启用一个数据源。",
        "Custom: %d": "自定义：%d",
        "5h usage: %d%%": "5 小时使用率：%d%%",
        "Weekly usage: %d%%": "每周使用率：%d%%",
        "Limit Hints Connector": "Codex 限额提示连接器",
        "Use Codex Limit Hints Connector": "使用 Codex 限额提示连接器",
        "Asks the local Codex CLI app-server for account/rateLimits/read. TokenPilot does not read, store, display, or export Codex access tokens.": "选择性测试功能：通过本地 Codex CLI app-server 调用 account/rateLimits/read。TokenPilot 不读取、保存、显示或导出 Codex access token。",
        "Codex app-server limit hints are unofficial and may break if the Codex CLI changes. Disable to fall back to local activity/manual values.": "通过 Codex CLI app-server 的非官方测试功能；数值只是提示，不保证是官方配额。关闭后会回退到本地活动/手动数值。",
        "Manual / personal calibration fallback": "手动限额提示备用",
        "Remaining %d%%": "剩余 %d%%",
        "Providers": "提供方",
        "Limit": "额度",
        "Next reset": "下次重置",
        "Last updated": "最后更新",
        "Stable": "稳定",
        "Warning": "注意",
        "Critical": "危险",
        "No reset": "无重置信息",
        "Local log": "本地日志",
        "Local source": "本地来源",
        "Not web quota": "不是网页配额",
        "Export": "导出",
        "Format": "格式",
        "Save": "保存",
        "Exports the selected History period only. Credentials, tokens, chat IDs, webhooks, and local file paths are not included.": "导出所选历史用量和提供方摘要。不会包含凭据、密钥 Token、聊天 ID、Webhook、本地文件路径或原始提示/回复文本。",
        "Preview sample data when no source is connected": "未连接数据源时预览示例数据",
        "Sample preview is optional and off by default so release builds never look connected before setup.": "示例预览是可选项且默认关闭，因此发布版本在设置前不会看起来像已连接。",
        "macOS": "macOS",
        "TG": "TG",
        "DC": "DC",
        "Telegram": "Telegram",
        "Discord": "Discord",
        "Alerts": "提醒",
        "Daily challenge": "每日挑战",
        "Daily challenge target": "挑战目标",
        "Daily": "每日",
        "Week": "每周",
        "5h": "5小时",
        "Token saved securely": "Token 已安全保存",
        "Telegram token saved in TokenPilot Keychain item.": "Telegram Token 已保存到 TokenPilot Keychain 项。",
        "Telegram token deleted.": "Telegram Token 已删除。",
        "Telegram test message sent.": "Telegram 测试消息已发送。",
        "Chat ID found.": "已找到聊天 ID。",
        "No usage data": "无使用量数据",
        "No data source connected": "未连接数据源",
        "Invalid JSON": "无效 JSON",
        "STALE · older than 2 minutes": "过期 · 超过 2 分钟",
        "No gemini_cli.api_response events yet": "尚无 gemini_cli.api_response 事件",
        "Telemetry file could not be read": "无法读取 telemetry 文件",
        "Parsed /status": "已解析 /status",
        "Parse status first": "请先解析状态",
        "Parse /status": "解析 /status",
        "Copy": "复制",
        "Connected": "已连接",
        "Not configured": "未配置",
        "Failed": "失败",
        "Ready": "就绪",
        "TokenPilot": "TokenPilot",
        "Language changes may require restarting TokenPilot.": "语言变更可能需要重启 TokenPilot。",
        "No telemetry yet": "尚无 telemetry",
        "Overview": "概览",
        "History": "历史",
        "Settings": "设置",
        "Status": "状态",
        "Notification permission: %@": "通知权限：%@",
        "Today": "今天",
        "Last 7 days": "过去 7 天",
        "This month": "本月",
        "Total tokens": "总计 Token",
        "Input tokens": "输入 Token",
        "Output tokens": "输出 Token",
        "Cache tokens": "缓存 Token",
        "Most used": "最常用",
        "Busiest hour": "高峰时间",
        "Requests": "请求数",
        "Est. cost": "预估费用",
        "ON": "开",
        "OFF": "关",
        "Risk": "风险",
        "Period": "周期",
        "Recent usage": "最近使用量",
        "No data": "无数据",
        "Connect a data source.": "请连接数据源。",
        "tok": "令牌",
        "Use Codex Web Snapshot": "使用手动限额快照",
        "Enter values you see on Codex web. TokenPilot stores only these numbers, not cookies or login tokens.": "输入你手动看到的限额数值。TokenPilot 只保存这些数字，不保存 Cookie 或登录 Token。",
        "Web today tokens: %d": "手动今日 Token：%d",
        "Mark Web Snapshot Now": "将手动快照标记为当前",
        "Captured": "捕获时间",
        "Codex web snapshot marked as current.": "已将 Codex 手动快照标记为当前。",
        "defaultClaudePath": "~/Library/Application Support/TokenPilot/claude-statusline.json",
        "defaultGeminiPath1": "~/.gemini/telemetry.log",
        "defaultGeminiPath2": "project-level .gemini/telemetry.log",
        "est.": "估计",
        "Estimated": "估计",
        "Connect Claude JSONL or Gemini telemetry to fill token charts.": "连接 Claude JSONL 或 Gemini telemetry 以填充 Token 图表。",
        "No token event history yet": "尚无 Token 事件历史",
        "Latest limit signals": "最新限额信号",
        "Limit signals are recorded even when token event history is not available.": "即使没有 Token 事件历史，也会记录限额信号。",
        "Show latest limit signals": "展开最新限额信号",
        "Hide latest limit signals": "折叠最新限额信号",
        "Showing limit signals until token events arrive.": "在 Token 事件到达前显示限额信号。",
        "Granted": "已授权",
        "Denied": "已拒绝",
        "Not requested": "未请求",
        "Unknown": "未知",
        "High": "高",
        "Medium": "中",
        "Low": "低",
        "high": "高",
        "medium": "中",
        "low": "低",
        "Manual": "手动",
        "manual": "手动",
        "alert.reset.title": "TokenPilot 重置",
        "alert.fifty.title": "TokenPilot 50%",
        "alert.eighty.title": "TokenPilot 80%",
        "alert.hundred.title": "TokenPilot 已达上限",
        "alert.reset.body": "TokenPilot\n\n%@ 重置已完成。\n可以继续使用。",
        "alert.fifty.body": "TokenPilot\n\n%@ 已达 50%。\n重置：%@",
        "alert.eighty.body": "TokenPilot\n\n%@\n使用率：%d%%\n重置：%@\n\n建议：\n在重置前使用 %@。",
        "alert.hundred.body": "TokenPilot\n\n%@ 已达 100%。\n重置倒计时：%@\n\n建议切换至：\n%@",
        "alert.or": " 或 ",
        "Telegram is not configured.": "Telegram 未配置。",
        "Telegram URL is invalid.": "Telegram URL 无效。",
        "Telegram request failed.": "Telegram 请求失败。",
        "No chat ID found. Send a message to the bot first.": "未找到聊天 ID。请先向机器人发送一条消息。",
        "Discord webhook is not configured.": "Discord Webhook 未配置。",
        "Discord webhook URL is invalid.": "Discord Webhook URL 无效。",
        "Discord request failed.": "Discord 请求失败。",
        "Keychain item contained invalid data.": "Keychain 项目包含无效数据。",
        "Keychain.status.error": "Keychain 返回状态 %d。"
    ]

    private static let japaneseFallback: [String: String] = [
        "Claude Code": "Claude Code",
        "Codex": "Codex",
        "Gemini CLI": "Gemini CLI",
        "LIVE": "LIVE",
        "STALE": "古い",
        "MOCK": "モック",
        "--": "--",
        "Input": "入力",
        "Output": "出力",
        "Cost": "コスト",
        "System Default": "システム既定",
        "Local AI usage cockpit": "ローカル AI 使用量ユーティリティ",
        "Connect providers in Settings": "設定でデータソースを接続",
        "Connect a provider in Settings": "設定でデータソースを接続してください",
        "Today tokens": "今日のトークン",
        "Highest risk": "最大リスク",
        "Lowest remaining": "残り最少",
        "Nearest reset": "次のリセット",
        "No limits": "制限情報なし",
        "Avg/request": "平均/リクエスト",
        "Daily cap": "日次上限",
        "Token saved": "Token 保存済み",
        "No token": "Token なし",
        "No chat ID": "Chat ID なし",
        "Chat ID set": "Chat ID 設定済み",
        "Enter a bot token first.": "先に Bot Token を入力してください。",
        "Telegram OFF by default. Enable only after saving TokenPilot's own bot token.": "Telegram は既定でオフです。TokenPilot 専用 Bot Token を保存してから有効にしてください。",
        "Discord notifications": "Discord 通知",
        "Enable Discord Alerts": "Discord 通知を有効化",
        "Saved webhook hidden": "保存済み Webhook は非表示",
        "Discord Webhook URL": "Discord Webhook URL",
        "Webhook saved": "Webhook 保存済み",
        "Webhook saved securely": "Webhook 保存済み",
        "No webhook": "Webhook なし",
        "Save Webhook": "Webhook を保存",
        "Replace Webhook": "Webhook を置換",
        "Delete Webhook": "Webhook を削除",
        "Discord webhook saved in TokenPilot Keychain item.": "Discord Webhook を TokenPilot Keychain 項目に保存しました。",
        "Discord webhook deleted.": "Discord Webhook を削除しました。",
        "Discord test message sent.": "Discord テストメッセージを送信しました。",
        "Enter a Discord webhook URL first.": "先に Discord Webhook URL を入力してください。",
        "Discord OFF by default. Paste only a Discord channel webhook created for TokenPilot.": "Discord は既定でオフです。TokenPilot 用に作成した Discord チャンネル Webhook だけを貼り付けてください。",
        "Webhook URL is stored in TokenPilot's own Keychain item and is never shown in plain text after saving.": "Webhook URL は TokenPilot 専用 Keychain 項目に保存され、保存後は平文表示されません。",
        "Optional Discord Alerts": "任意の Discord 通知",
        "Create a Discord channel webhook, paste it once, then send a test message.": "Discord チャンネル Webhook を作成し、一度貼り付けてからテストメッセージを送信します。",
        "Telegram and Discord send only alert messages when enabled.": "有効時、Telegram と Discord は通知メッセージだけを送信します。",
        "✅ TokenPilot test alert. Discord notifications are connected.": "✅ TokenPilot テスト通知です。Discord 通知が接続されました。",
        "Choose telemetry.log": "telemetry.log を選択",
        "Choose your Gemini CLI telemetry log file.": "Gemini CLI telemetry ログファイルを選択してください。",
        "Choose Claude status JSON": "Claude 状態 JSON を選択",
        "Choose the Claude statusline JSON file TokenPilot should read.": "TokenPilot が読む Claude statusline JSON ファイルを選択してください。",
        "Choose Gemini source": "Gemini ソースを選択",
        "Choose telemetry.log or a Gemini session folder.": "telemetry.log または Gemini セッションフォルダを選択してください。",
        "Telemetry source": "Telemetry ソース",
        "You can select telemetry.log or a .gemini session folder.": "telemetry.log または .gemini セッションフォルダを選択できます。",
        "Selected source path saved, but sandbox bookmark was not created. Choose it again if the sandbox cannot read it.": "ソースパスは保存されましたが、サンドボックス用ブックマークを作成できませんでした。サンドボックスで読めない場合は選択し直してください。",
        "Toggle providers shown on Overview. Disabled providers are hidden and not refreshed.": "概要に表示するプロバイダを切り替えます。無効にしたプロバイダは非表示になり、更新されません。",
        "Auto-detect sources": "データソースを自動検出",
        "Scans only local default paths and user-selected files.": "ローカルの既定パスとユーザーが選択したファイルだけをスキャンします。",
        "Menu bar status": "メニューバー状態",
        "Current menu bar": "現在のメニューバー",
        "Show selected provider in the menu bar. Disabled providers are skipped.": "選択したプロバイダをメニューバーに表示します。無効なプロバイダはスキップします。",
        "At least one provider must stay enabled.": "少なくとも1つのプロバイダを有効にしてください。",
        "Custom: %d": "カスタム：%d",
        "5h usage: %d%%": "5時間使用率：%d%%",
        "Weekly usage: %d%%": "週次使用率：%d%%",
        "Remaining %d%%": "残り %d%%",
        "Providers": "プロバイダー",
        "Limit": "上限",
        "Next reset": "次のリセット",
        "Last updated": "最終更新",
        "Stable": "安定",
        "Warning": "注意",
        "Critical": "危険",
        "No reset": "リセット情報なし",
        "Limit Hints Connector": "Codex 上限ヒントコネクタ",
        "Use Codex Limit Hints Connector": "Codex 上限ヒントコネクタを使う",
        "Asks the local Codex CLI app-server for account/rateLimits/read. TokenPilot does not read, store, display, or export Codex access tokens.": "任意のベータ機能です。ローカルの Codex CLI app-server に account/rateLimits/read を依頼します。TokenPilot は Codex アクセストークンを読み取り・保存・表示・書き出しません。",
        "Codex app-server limit hints are unofficial and may break if the Codex CLI changes. Disable to fall back to local activity/manual values.": "Codex CLI app-server 経由の非公式ベータです。値はヒントであり、公式上限として保証されません。オフにするとローカル活動量/手動値に戻ります。",
        "Manual / personal calibration fallback": "手動上限ヒントのフォールバック",
        "Use Codex Web Snapshot": "手動上限スナップショットを使う",
        "Enter values you see on Codex web. TokenPilot stores only these numbers, not cookies or login tokens.": "自分で確認した上限値を入力します。TokenPilotはCookieやログイントークンではなく数値だけを保存します。",
        "Web today tokens: %d": "手動今日トークン：%d",
        "Mark Web Snapshot Now": "手動スナップショットを現在時刻にする",
        "Captured": "取得時刻",
        "Codex web snapshot marked as current.": "Codex 手動スナップショットを現在時刻にしました。",
        "Local log": "ローカルログ",
        "Local source": "ローカルソース",
        "Not web quota": "Web枠ではありません",
        "Export": "書き出し",
        "Format": "形式",
        "Save": "保存",
        "Exports the selected History period only. Credentials, tokens, chat IDs, webhooks, and local file paths are not included.": "選択した履歴の使用量とプロバイダー概要を書き出します。認証情報、シークレットトークン、チャットID、Webhook、ローカルファイルパス、元のプロンプト/応答本文は含まれません。",
        "Preview sample data when no source is connected": "データソース未接続時にサンプルデータをプレビュー",
        "Sample preview is optional and off by default so release builds never look connected before setup.": "サンプルプレビューは任意で既定ではオフです。リリース版が設定前に接続済みのように見えることはありません。",
        "macOS": "macOS",
        "TG": "TG",
        "Telegram": "Telegram",
        "Alerts": "通知",
        "Daily challenge": "デイリーチャレンジ",
        "Daily challenge target": "チャレンジ目標",
        "Daily": "日次",
        "Week": "週次",
        "5h": "5時間",
        "Token saved securely": "Token を安全に保存しました",
        "Telegram token saved in TokenPilot Keychain item.": "Telegram Token を TokenPilot Keychain 項目に保存しました。",
        "Telegram token deleted.": "Telegram Token を削除しました。",
        "Telegram test message sent.": "Telegram テストメッセージを送信しました。",
        "Chat ID found.": "Chat ID を見つけました。",
        "No usage data": "使用量データなし",
        "No data source connected": "データソース未接続",
        "Invalid JSON": "無効な JSON",
        "STALE · older than 2 minutes": "古い · 2分以上前",
        "No gemini_cli.api_response events yet": "gemini_cli.api_response イベントはまだありません",
        "Telemetry file could not be read": "telemetry ファイルを読み取れません",
        "Parsed /status": "/status 解析済み",
        "Parse status first": "先に status を解析してください",
        "Parse /status": "/status を解析",
        "Copy": "コピー",
        "Connected": "接続済み",
        "Not configured": "未設定",
        "Failed": "失敗",
        "Ready": "準備完了",
        "TokenPilot": "TokenPilot",
        "Language changes may require restarting TokenPilot.": "言語変更には TokenPilot の再起動が必要な場合があります。",
        "No telemetry yet": "telemetry はまだありません",
        "Overview": "概要",
        "History": "履歴",
        "Settings": "設定",
        "Status": "状態",
        "Notification permission: %@": "通知許可: %@",
        "Today": "今日",
        "Last 7 days": "過去7日",
        "This month": "今月",
        "Total tokens": "合計トークン",
        "Input tokens": "入力トークン",
        "Output tokens": "出力トークン",
        "Cache tokens": "キャッシュトークン",
        "Most used": "最も使用",
        "Busiest hour": "ピーク時",
        "Requests": "リクエスト数",
        "Est. cost": "推定コスト",
        "ON": "オン",
        "OFF": "オフ",
        "Risk": "リスク",
        "Period": "期間",
        "Recent usage": "直近の使用量",
        "No data": "データなし",
        "Connect a data source.": "データソースを接続してください。",
        "tok": "トークン",
        "defaultClaudePath": "~/Library/Application Support/TokenPilot/claude-statusline.json",
        "defaultGeminiPath1": "~/.gemini/telemetry.log",
        "defaultGeminiPath2": "project-level .gemini/telemetry.log",
        "est.": "推定",
        "Estimated": "推定",
        "Connect Claude JSONL or Gemini telemetry to fill token charts.": "Claude JSONL または Gemini telemetry を接続してトークンチャートを表示します。",
        "No token event history yet": "トークンイベント履歴がまだありません",
        "Latest limit signals": "最新の制限シグナル",
        "Limit signals are recorded even when token event history is not available.": "トークンイベント履歴がなくても制限シグナルは記録されます。",
        "Show latest limit signals": "最新の制限シグナルを表示",
        "Hide latest limit signals": "最新の制限シグナルを隠す",
        "Showing limit signals until token events arrive.": "トークンイベントが届くまで制限シグナルを表示します。",
        "DC": "DC",
        "Discord": "Discord",
        "Granted": "許可済み",
        "Denied": "拒否",
        "Not requested": "未リクエスト",
        "Unknown": "不明",
        "High": "高",
        "Medium": "中",
        "Low": "低",
        "high": "高",
        "medium": "中",
        "low": "低",
        "Manual": "手動",
        "manual": "手動",
        "alert.reset.title": "TokenPilot リセット",
        "alert.fifty.title": "TokenPilot 50%",
        "alert.eighty.title": "TokenPilot 80%",
        "alert.hundred.title": "TokenPilot 上限到達",
        "alert.reset.body": "TokenPilot\n\n%@ リセット完了。\n継続して使用できます。",
        "alert.fifty.body": "TokenPilot\n\n%@ が 50％ に達しました。\nリセット：%@",
        "alert.eighty.body": "TokenPilot\n\n%@\n使用率：%d%%\nリセット：%@\n\n提案：\nリセットまで %@ を使用してください。",
        "alert.hundred.body": "TokenPilot\n\n%@ が 100％ に達しました。\nリセットまで：%@\n\n切り替え先：\n%@",
        "alert.or": " または ",
        "Telegram is not configured.": "Telegram が設定されていません。",
        "Telegram URL is invalid.": "Telegram URL が無効です。",
        "Telegram request failed.": "Telegram リクエストに失敗しました。",
        "No chat ID found. Send a message to the bot first.": "Chat ID が見つかりません。先にボットにメッセージを送信してください。",
        "Discord webhook is not configured.": "Discord Webhook が設定されていません。",
        "Discord webhook URL is invalid.": "Discord Webhook URL が無効です。",
        "Discord request failed.": "Discord リクエストに失敗しました。",
        "Keychain item contained invalid data.": "キーチェーン項目に無効なデータが含まれています。",
        "Keychain.status.error": "キーチェーンがステータス %d を返しました。"
    ]

    private static let koreanFallback: [String: String] = [
        "macOS": "macOS",
        "TG": "TG",
        "DC": "DC",
        "Discord": "디스코드",
        "Overview": "개요",
        "History": "기록",
        "Settings": "설정",
        "Local AI usage cockpit": "로컬 AI 사용량 유틸리티",
        "Screen": "화면",
        "Refresh": "새로고침",
        "Refreshing": "새로고침 중",
        "Quit": "종료",
        "Dismiss": "닫기",
        "Alerts": "알림",
        "ON": "켜짐",
        "OFF": "꺼짐",
        "Reset": "리셋",
        "Today": "오늘",
        "Last 7 days": "최근 7일",
        "This month": "이번 달",
        "History period": "기록 기간",
        "Simple history": "간단 기록",
        "No history yet": "아직 기록이 없습니다",
        "Connect a data source or keep mock data enabled.": "데이터 소스를 연결하거나 목업 데이터를 켜두세요.",
        "tok": "토큰",
        "1. Data Sources": "1. 데이터 소스",
        "2. Notifications": "2. 알림",
        "3. Telegram": "3. 텔레그램",
        "4. Discord": "4. 디스코드",
        "4. Language": "4. 언어",
        "5. Language": "5. 언어",
        "5. Setup Guide": "5. 설정 가이드",
        "6. Setup Guide": "6. 설정 가이드",
        "6. Privacy": "6. 개인정보 보호",
        "7. Privacy": "7. 개인정보 보호",
        "Data Sources": "데이터 소스",
        "Provider Diagnostics": "제공자 진단",
        "Before diagnostics, TokenPilot checks local usage metadata and selected files only. It excludes prompts, responses, secrets, credentials, browser cookies, raw events, and raw paths from summaries and exports.": "진단 전에 TokenPilot은 로컬 사용량 메타데이터와 사용자가 선택한 파일만 확인합니다. 요약과 내보내기에는 프롬프트, 응답, 비밀값, 인증정보, 브라우저 쿠키, 원본 이벤트, 원본 경로를 포함하지 않습니다.",
        "Check all providers": "모든 제공자 확인",
        "Last checked": "마지막 확인",
        "Never checked": "확인 전",
        "Refresh or re-check when usage looks stale.": "사용량이 오래되어 보이면 새로고침하거나 다시 확인하세요.",
        "Choose a local source or run Auto-detect.": "로컬 소스를 선택하거나 자동 감지를 실행하세요.",
        "Grant macOS file access or choose the source again.": "macOS 파일 접근 권한을 허용하거나 소스를 다시 선택하세요.",
        "Verify the provider writes usage metadata, then check again.": "제공자가 사용량 메타데이터를 기록하는지 확인한 뒤 다시 검사하세요.",
        "Run the provider CLI, then refresh TokenPilot.": "제공자 CLI를 실행한 뒤 TokenPilot을 새로고침하세요.",
        "Choose a valid metadata file or reset the configured source.": "올바른 메타데이터 파일을 선택하거나 설정된 소스를 초기화하세요.",
        "Enable this provider if you want it on Overview.": "개요에 표시하려면 이 제공자를 켜세요.",
        "Paste /status or enter manual estimates.": "/status를 붙여넣거나 수동 추정값을 입력하세요.",
        "Review the manual estimate and confidence label.": "수동 추정값과 신뢰도 라벨을 확인하세요.",
        "Provider metadata is readable. Raw paths and events stay hidden from diagnostics.": "제공자 메타데이터를 읽을 수 있습니다. 원본 경로와 이벤트는 진단에서 숨깁니다.",
        "No readable source was found in the configured/default locations.": "설정된 위치나 기본 위치에서 읽을 수 있는 소스를 찾지 못했습니다.",
        "A candidate source exists but macOS did not allow TokenPilot to read it.": "후보 소스는 있지만 macOS가 TokenPilot의 읽기를 허용하지 않았습니다.",
        "A source was found, but it did not contain usable usage metadata.": "소스를 찾았지만 사용할 수 있는 사용량 메타데이터가 없습니다.",
        "The latest usable metadata is older than expected.": "마지막 사용 가능한 메타데이터가 예상보다 오래되었습니다.",
        "The selected source exists but does not match the expected metadata format.": "선택한 소스는 있지만 예상한 메타데이터 형식과 맞지 않습니다.",
        "This provider is disabled and skipped during refresh.": "이 제공자는 꺼져 있으며 새로고침에서 건너뜁니다.",
        "Codex is waiting for pasted /status output or manual estimates.": "Codex는 붙여넣은 /status 출력 또는 수동 추정값을 기다리고 있습니다.",
        "TokenPilot is using manual or unofficial estimate data.": "TokenPilot이 수동 또는 비공식 추정 데이터를 사용하고 있습니다.",
        "Run Provider Diagnostics in Settings to connect Claude, Codex, or Gemini.": "설정의 제공자 진단에서 Claude, Codex, Gemini를 연결하세요.",
        "Open Provider Diagnostics": "제공자 진단 열기",
        "Notifications": "알림",
        "Telegram": "텔레그램",
        "Language": "언어",
        "Setup Guide": "설정 가이드",
        "Privacy": "개인정보 보호",
        "Connect providers in Settings": "설정에서 데이터 소스를 연결하세요",
        "Daily challenge": "일일 챌린지",
        "Daily challenge target": "챌린지 목표",
        "Highest risk": "최고 위험",
        "Lowest remaining": "가장 적게 남은 한도",
        "Nearest reset": "가장 가까운 리셋",
        "TokenPilot": "TokenPilot",
        "Today tokens": "오늘 토큰",
        "Status file path": "상태 파일 경로",
        "Claude status path": "Claude 상태 경로",
        "Check Connection": "연결 확인",
        "Telemetry log file": "텔레메트리 로그 파일",
        "Choose…": "선택…",
        "Default suggestions:": "기본 제안:",
        "Manual / estimated mode": "수동 / 추정 모드",
        "Limit Hints Connector": "Codex 한도 힌트 커넥터",
        "Use Codex Limit Hints Connector": "Codex 한도 힌트 커넥터 사용",
        "Asks the local Codex CLI app-server for account/rateLimits/read. TokenPilot does not read, store, display, or export Codex access tokens.": "선택 베타 기능입니다. 로컬 Codex CLI app-server에 account/rateLimits/read를 요청합니다. TokenPilot은 Codex access token을 읽거나 저장하거나 표시하거나 내보내지 않습니다.",
        "Codex app-server limit hints are unofficial and may break if the Codex CLI changes. Disable to fall back to local activity/manual values.": "Codex CLI app-server 경유 비공식 베타입니다. 값은 공식 한도 보장값이 아닌 힌트입니다. 끄면 로컬 활동량/수동값으로 돌아갑니다.",
        "Manual / personal calibration fallback": "수동 한도 힌트 fallback",
        "Use Codex Web Snapshot": "수동 한도 스냅샷 사용",
        "Enter values you see on Codex web. TokenPilot stores only these numbers, not cookies or login tokens.": "직접 확인한 한도 값을 입력하세요. TokenPilot은 쿠키나 로그인 토큰 없이 숫자만 저장합니다.",
        "Web today tokens: %d": "수동 오늘 토큰: %d",
        "Mark Web Snapshot Now": "수동 스냅샷 현재로 표시",
        "Captured": "캡처 시각",
        "Codex web snapshot marked as current.": "Codex 수동 스냅샷을 현재 시각으로 표시했습니다.",
        "Plan label": "플랜 라벨",
        "Reset time": "리셋 시간",
        "Notes": "메모",
        "Pasted /status output": "붙여넣은 /status 출력",
        "Paste Status": "Status 붙여넣기",
        "Parse Status": "Status 파싱",
        "Confidence": "신뢰도",
        "Parsed status is marked medium or low confidence unless clearly reliable.": "파싱한 상태는 명확히 신뢰 가능하지 않으면 중간 또는 낮은 신뢰도로 표시됩니다.",
        "Global notifications": "전체 알림",
        "macOS notifications": "macOS 알림",
        "Telegram notifications": "텔레그램 알림",
        "Discord notifications": "디스코드 알림",
        "Request Notification Permission": "알림 권한 요청",
        "Send Test Notification": "테스트 알림 보내기",
        "Status": "상태",
        "Permission denied. Enable notifications in macOS Settings > Notifications.": "권한이 거부되었습니다. macOS 설정 > 알림에서 TokenPilot 알림을 켜주세요.",
        "Provider/window alert rules": "제공자/윈도우별 알림 규칙",
        "Enable Telegram Alerts": "텔레그램 알림 켜기",
        "Enable Discord Alerts": "디스코드 알림 켜기",
        "Saved token hidden": "저장된 토큰은 숨겨짐",
        "Saved webhook hidden": "저장된 Webhook은 숨겨짐",
        "Bot Token": "봇 토큰",
        "Discord Webhook URL": "디스코드 Webhook URL",
        "Chat ID": "채팅 ID",
        "Save Token": "토큰 저장",
        "Replace Token": "토큰 교체",
        "Delete Token": "토큰 삭제",
        "Save Webhook": "Webhook 저장",
        "Replace Webhook": "Webhook 교체",
        "Delete Webhook": "Webhook 삭제",
        "Find Chat ID": "채팅 ID 찾기",
        "Send Test Message": "테스트 메시지 보내기",
        "Connection status": "연결 상태",
        "Last test sent at": "마지막 테스트 전송",
        "Telegram alerts are optional. TokenPilot stores only its own bot token Keychain item and sends only alert messages when enabled.": "텔레그램 알림은 선택 사항입니다. TokenPilot은 자체 봇 토큰 Keychain 항목만 저장하고, 켜진 경우 알림 메시지만 보냅니다.",
        "Language changes may require restarting TokenPilot.": "언어 변경은 TokenPilot 재시작이 필요할 수 있습니다.",
        "Connect Claude Code": "Claude Code 연결",
        "Connect Gemini CLI": "Gemini CLI 연결",
        "Add Codex status": "Codex 상태 추가",
        "Enable Notifications": "알림 켜기",
        "Optional Telegram Alerts": "선택 사항: 텔레그램 알림",
        "Optional Discord Alerts": "선택 사항: 디스코드 알림",
        "Not checked": "확인 안 됨",
        "Manual mode": "수동 모드",
        "TokenPilot reads the Claude statusline snapshot below.": "TokenPilot은 아래 Claude statusline 스냅샷을 읽습니다.",
        "Enable local telemetry and choose telemetry.log.": "로컬 텔레메트리를 켜고 telemetry.log를 선택하세요.",
        "Run /status in Codex CLI and paste the result.": "Codex CLI에서 /status를 실행한 뒤 결과를 붙여넣으세요.",
        "Request Permission": "권한 요청",
        "Request macOS permission, then send a test alert.": "macOS 권한을 요청한 뒤 테스트 알림을 보내세요.",
        "Create a bot with BotFather, send it a message, paste token and chat ID, then test.": "BotFather로 봇을 만들고 메시지를 보낸 뒤 토큰과 채팅 ID를 붙여넣고 테스트하세요.",
        "Create a Discord channel webhook, paste it once, then send a test message.": "디스코드 채널 Webhook을 만들고 한 번 붙여넣은 뒤 테스트 메시지를 보내세요.",
        "Preview sample data when no source is connected": "소스가 연결되지 않았을 때 샘플 데이터 미리보기",
        "Sample preview is optional and off by default so release builds never look connected before setup.": "샘플 미리보기는 선택 사항이며 기본 꺼짐입니다. 따라서 릴리스 빌드가 설정 전부터 연결된 것처럼 보이지 않습니다.",
        "Show mock data when no source is connected": "소스가 연결되지 않았을 때 목업 데이터 표시",
        "Reads local usage metadata and selected files only.": "로컬 사용량 메타데이터와 선택한 파일만 읽습니다.",
        "Does not read browser cookies, hidden credentials, or other Keychain items.": "브라우저 쿠키, 숨겨진 인증정보, 다른 Keychain 항목은 읽지 않습니다.",
        "Does not read browser cookies or other Keychain items.": "브라우저 쿠키나 다른 Keychain 항목은 읽지 않습니다.",
        "Codex Limit Hints Connector is opt-in and asks the local Codex CLI app-server for account/rateLimits/read; TokenPilot never reads, displays, or stores Codex access tokens.": "Codex 한도 힌트 커넥터는 기본 꺼짐인 비공식 베타입니다. 켜진 경우 로컬 Codex CLI app-server만 호출하며, TokenPilot은 Codex access token을 읽거나 표시하거나 저장하지 않습니다.",
        "Codex v1 is manual/estimated only; TokenPilot never calls private endpoints.": "공식 안정 한도 소스가 생기기 전까지 Codex 값은 수동/로컬 로그/선택 베타 힌트로 표시합니다.",
        "Telegram sends only alert messages when enabled.": "텔레그램은 켜진 경우 알림 메시지만 보냅니다.",
        "Telegram and Discord send only alert messages when enabled.": "텔레그램과 디스코드는 켜진 경우 알림 메시지만 보냅니다.",
        "Discord OFF by default. Paste only a Discord channel webhook created for TokenPilot.": "디스코드는 기본 꺼짐입니다. TokenPilot용으로 만든 디스코드 채널 Webhook만 붙여넣으세요.",
        "Webhook URL is stored in TokenPilot's own Keychain item and is never shown in plain text after saving.": "Webhook URL은 TokenPilot 자체 Keychain 항목에 저장되며, 저장 후 평문으로 표시하지 않습니다.",
        "STALE": "오래됨",
        "Ready": "준비됨",
        "Daily": "일일",
        "Week": "주간",
        "5h": "5시간",
        "Total tokens": "전체 토큰",
        "Input tokens": "입력 토큰",
        "Output tokens": "출력 토큰",
        "Cache tokens": "캐시 토큰",
        "Requests": "요청 수",
        "Est. cost": "예상 비용",
        "Most used": "최다 사용",
        "Busiest hour": "가장 바쁜 시간",
        "7-day usage": "7일 사용량",
        "Provider share": "제공자 비중",
        "Copy": "복사",
        "Connected": "연결됨",
        "Not configured": "설정 안 됨",
        "Failed": "실패",
        "No data source connected": "데이터 소스 미연결",
        "Invalid JSON": "잘못된 JSON",
        "STALE · older than 2 minutes": "오래됨 · 2분 이상 지남",
        "No telemetry yet": "아직 텔레메트리가 없습니다",
        "No gemini_cli.api_response events yet": "아직 gemini_cli.api_response 이벤트가 없습니다",
        "Telemetry file could not be read": "텔레메트리 파일을 읽을 수 없습니다",
        "Parsed /status": "파싱된 /status",
        "Parse status first": "먼저 상태를 파싱하세요",
        "Parse /status": "상태 파싱",
        "Token saved securely": "토큰이 안전하게 저장됨",
        "No usage data": "사용량 데이터 없음",
        "Test notification sent.": "테스트 알림이 전송되었습니다.",
        "No notification channel is enabled or configured.": "켜져 있거나 설정 완료된 알림 채널이 없습니다.",
        "Copied.": "복사됨.",
        "Telegram token saved in TokenPilot Keychain item.": "TokenPilot 키체인 항목에 봇 토큰이 저장되었습니다.",
        "Telegram token deleted.": "텔레그램 토큰이 삭제되었습니다.",
        "Telegram test message sent.": "텔레그램 테스트 메시지를 전송했습니다.",
        "Discord test message sent.": "디스코드 테스트 메시지를 전송했습니다.",
        "Discord webhook saved in TokenPilot Keychain item.": "TokenPilot 키체인 항목에 디스코드 Webhook이 저장되었습니다.",
        "Discord webhook deleted.": "디스코드 Webhook이 삭제되었습니다.",
        "Enter a Discord webhook URL first.": "먼저 디스코드 Webhook URL을 입력하세요.",
        "Webhook saved": "Webhook 저장됨",
        "Webhook saved securely": "Webhook이 안전하게 저장됨",
        "No webhook": "Webhook 없음",
        "Chat ID found.": "채팅 ID를 찾았습니다.",
        "Notification permission: %@": "알림 권한: %@",
        "✅ TokenPilot test alert. macOS notifications are connected.": "✅ TokenPilot 테스트 알림입니다. macOS 알림이 연결되었습니다.",
        "✅ TokenPilot test alert. Telegram notifications are connected.": "✅ TokenPilot 테스트 알림입니다. Telegram 알림이 연결되었습니다.",
        "✅ TokenPilot test alert. Discord notifications are connected.": "✅ TokenPilot 테스트 알림입니다. Discord 알림이 연결되었습니다.",
        "Suggestion": "권장",
        "Use Codex or Gemini CLI until reset.": "리셋될 때까지 Codex 또는 Gemini CLI를 사용하세요.",
        "Suggested switch": "권장 전환",
        "high": "높음",
        "medium": "중간",
        "low": "낮음",
        "manual": "수동",
        "High": "높음",
        "Medium": "보통",
        "Low": "낮음",
        "Manual": "수동",
        "Not requested": "요청 안 함",
        "Granted": "허용됨",
        "Denied": "거부됨",
        "Unknown": "알 수 없음",
        "—": "—",
        "Connect Claude statusline": "Claude statusline을 연결하세요",
        "Codex status": "Codex 상태",
        "Risk": "위험",
        "Period": "기간",
        "Recent usage": "최근 사용량",
        "No data": "데이터 없음",
        "Connect a data source.": "데이터 소스를 연결하세요.",
        "defaultClaudePath": "~/Library/Application Support/TokenPilot/claude-statusline.json",
        "defaultGeminiPath1": "~/.gemini/telemetry.log",
        "defaultGeminiPath2": "project-level .gemini/telemetry.log",
        "est.": "추정",
        "Estimated": "추정",
        "Claude Code": "Claude Code",
        "Codex": "Codex",
        "Gemini CLI": "Gemini CLI",
        "LIVE": "LIVE",
        "MOCK": "MOCK",
        "--": "--",
        "Input": "입력",
        "Output": "출력",
        "Cost": "비용",
        "System Default": "시스템 기본값",
        "English": "English",
        "简体中文": "简体中文",
        "日本語": "日本語",
        "Toggle providers shown on Overview. Disabled providers are hidden and not refreshed.": "개요에 표시할 제공자를 선택합니다. 꺼진 제공자는 숨기고 새로고침하지 않지만 데이터는 삭제하지 않습니다.",
        "Auto-detect sources": "소스 자동 감지",
        "Scans only local default paths and user-selected files.": "로컬 기본 경로와 사용자가 선택한 파일만 확인합니다.",
        "Menu bar status": "메뉴바 상태",
        "Current menu bar": "현재 메뉴바",
        "Show selected provider in the menu bar. Disabled providers are skipped.": "선택한 제공자의 토큰 상태를 메뉴바에 표시합니다. 꺼진 제공자는 자동으로 건너뜁니다.",
        "At least one provider must stay enabled.": "최소 하나의 제공자는 켜져 있어야 합니다.",
        "Connect a provider in Settings": "설정에서 제공자를 연결하세요",
        "No limits": "제한 정보 없음",
        "Avg/request": "평균/요청",
        "Daily cap": "일일 한도",
        "Token saved": "토큰 저장됨",
        "No token": "토큰 없음",
        "No chat ID": "채팅 ID 없음",
        "Chat ID set": "채팅 ID 설정됨",
        "Enter a bot token first.": "먼저 봇 토큰을 입력하세요.",
        "Telegram OFF by default. Enable only after saving TokenPilot's own bot token.": "텔레그램은 기본 꺼짐입니다. TokenPilot 전용 봇 토큰을 저장한 뒤에만 켜세요.",
        "Choose telemetry.log": "telemetry.log 선택",
        "Choose your Gemini CLI telemetry log file.": "Gemini CLI telemetry 로그 파일을 선택하세요.",
        "Choose Claude status JSON": "Claude 상태 JSON 선택",
        "Choose the Claude statusline JSON file TokenPilot should read.": "TokenPilot이 읽을 Claude statusline JSON 파일을 선택하세요.",
        "Choose Gemini source": "Gemini 소스 선택",
        "Choose telemetry.log or a Gemini session folder.": "telemetry.log 또는 Gemini 세션 폴더를 선택하세요.",
        "Telemetry source": "텔레메트리 소스",
        "You can select telemetry.log or a .gemini session folder.": "telemetry.log 또는 .gemini 세션 폴더를 선택할 수 있습니다.",
        "Selected source path saved, but sandbox bookmark was not created. Choose it again if the sandbox cannot read it.": "소스 경로는 저장했지만 샌드박스 북마크를 만들지 못했습니다. 샌드박스에서 읽을 수 없으면 다시 선택하세요.",
        "Custom: %d": "사용자 지정: %d",
        "5h usage: %d%%": "5시간 사용률: %d%%",
        "Weekly usage: %d%%": "주간 사용률: %d%%",
        "Remaining %d%%": "남음 %d%%",
        "Providers": "제공자",
        "Limit": "한도",
        "Next reset": "다음 리셋",
        "Last updated": "업데이트",
        "Stable": "안정",
        "Warning": "주의",
        "Critical": "위험",
        "No reset": "리셋 정보 없음",
        "Local log": "로컬 로그",
        "Local source": "로컬 소스",
        "Not web quota": "웹 한도 아님",
        "Export": "내보내기",
        "Format": "형식",
        "Save": "저장",
        "Latest limit signals": "최근 한도 신호",
        "Limit signals are recorded even when token event history is not available.": "토큰 이벤트 기록이 없어도 한도 신호는 기록합니다.",
        "Show latest limit signals": "최근 한도 신호 펼치기",
        "Hide latest limit signals": "최근 한도 신호 접기",
        "No token event history yet": "아직 토큰 이벤트 기록이 없습니다",
        "Showing limit signals until token events arrive.": "토큰 이벤트가 들어오기 전까지 한도 신호를 보여줍니다.",
        "Connect Claude JSONL or Gemini telemetry to fill token charts.": "토큰 차트를 채우려면 Claude JSONL 또는 Gemini telemetry를 연결하세요.",
        "Exports the selected History period only. Credentials, tokens, chat IDs, webhooks, and local file paths are not included.": "선택한 기록 사용량과 제공자 요약을 내보냅니다. 자격 증명, 비밀 토큰, 채팅 ID, Webhook, 로컬 파일 경로, 원문 프롬프트/응답 본문은 포함하지 않습니다.",
        "alert.reset.title": "TokenPilot 초기화",
        "alert.fifty.title": "TokenPilot 50%",
        "alert.eighty.title": "TokenPilot 80%",
        "alert.hundred.title": "TokenPilot 한도 도달",
        "alert.reset.body": "TokenPilot\n\n%@ 초기화 완료.\n계속 사용할 수 있습니다.",
        "alert.fifty.body": "TokenPilot\n\n%@ 50%% 도달.\n리셋: %@",
        "alert.eighty.body": "TokenPilot\n\n%@\n사용량: %d%%\n리셋: %@\n\n제안:\n리셋까지 %@ 사용을 권장합니다.",
        "alert.hundred.body": "TokenPilot\n\n%@ 100%% 도달.\n리셋까지: %@\n\n전환 제안:\n%@",
        "alert.or": " 또는 ",
        "Telegram is not configured.": "Telegram이 설정되지 않았습니다.",
        "Telegram URL is invalid.": "Telegram URL이 올바르지 않습니다.",
        "Telegram request failed.": "Telegram 요청에 실패했습니다.",
        "No chat ID found. Send a message to the bot first.": "Chat ID를 찾을 수 없습니다. 봇에 먼저 메시지를 보내주세요.",
        "Discord webhook is not configured.": "Discord Webhook이 설정되지 않았습니다.",
        "Discord webhook URL is invalid.": "Discord Webhook URL이 올바르지 않습니다.",
        "Discord request failed.": "Discord 요청에 실패했습니다.",
        "Keychain item contained invalid data.": "키체인 항목에 유효하지 않은 데이터가 포함되어 있습니다.",
        "Keychain.status.error": "키체인이 상태 %d을(를) 반환했습니다."
    ]
}

public extension DataConfidence {
    func localizedLabel(language: TokenPilotLanguage) -> String {
        TokenPilotLocalizer.localized(label, language: language)
    }
}

public extension LimitWindowKind {
    func localizedLabel(language: TokenPilotLanguage) -> String {
        TokenPilotLocalizer.localized(label, language: language)
    }
}

public extension HistoryPeriod {
    func localizedLabel(language: TokenPilotLanguage) -> String {
        TokenPilotLocalizer.localized(label, language: language)
    }
}

public extension NotificationPermissionState {
    func localizedLabel(language: TokenPilotLanguage) -> String {
        TokenPilotLocalizer.localized(rawValue, language: language)
    }
}
